### ISSUE TITLE
Backend

### ISSUE THREAD

**Issue by AmineTir** [abderrahmane-tj/explorer#29]
- [x] Setup Koa server
- [x] Init routes structure
- [x] hook front-end to back-end
- [x] use PostgreSQL
- [x] `GET /root-nodes` route
- [x] `GET /nodes/:id` route
- [x] `GET /nodes-from-path/:path(.*)` route
- [x] `POST /nodes` route
- [x] `DELETE /nodes/:id` route
- [x] `PUT /nodes/:id` route

**Comment by atahrijouti** [comment]
@AmineTir  I've just realized that we need an update end-point for when you've clicked on create node, but you are in renaming state, and whatever you put there needs to be sent to the back-end to update the node name

**Comment by atahrijouti** [comment]
@AmineTir We should probably not close this issue until all the tasks on this issue are checked, don't you agree?

**Comment by abderrahmane-tj** [comment]
Creating a new Folder causes a server error as it thinks that `New Folder` already exists 🤷🏼
